/**
 * CSS build: concatenate style partials into a single obojima.css.
 * Adapted from the vtm-custom-foundry-system build to avoid @import races.
 *
 * Run with: node build-css.mjs   (from the obojima-atlas/ folder)
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const STYLES_DIR = join(import.meta.dirname, "styles");
const PARTIALS_DIR = join(STYLES_DIR, "partials");
const OUTPUT = join(STYLES_DIR, "obojima.css");

// Order matters: tokens/fonts first (the @import must be the first rule),
// then frame, then the panels.
const PARTIALS_ORDER = [
  "_fonts.css",
  "_tokens.css",
  "_frame.css",
  "_master.css",
  "_detail.css",
  "_potions.css",
  "_edit.css"
];

const banner = `/* GENERATED by build-css.mjs — do not edit directly. Edit styles/partials/*.css and rerun. */\n\n`;

const parts = PARTIALS_ORDER.map((name) => {
  const content = readFileSync(join(PARTIALS_DIR, name), "utf8");
  return `/* ===== ${name} ===== */\n${content}`;
});

writeFileSync(OUTPUT, banner + parts.join("\n\n"), "utf8");
console.log(`Wrote ${OUTPUT} (${PARTIALS_ORDER.length} partials).`);
