/**
 * One-off: fetch the OFL woff2 files (latin subset) used by the Atlas sheet from
 * Google Fonts into fonts/, and write styles/partials/_fonts.css with local
 * @font-face rules. This makes the system fully self-contained / offline.
 * Run: node fetch-fonts.mjs   (then: node build-css.mjs)
 */
import { writeFileSync, mkdirSync } from "fs";
import { createHash } from "crypto";
import { join } from "path";

const ROOT = import.meta.dirname;
const FONTS_DIR = join(ROOT, "fonts");
const OUT_CSS = join(ROOT, "styles", "partials", "_fonts.css");
mkdirSync(FONTS_DIR, { recursive: true });

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const FAMILIES = [
  { name: "Architects Daughter", slug: "architects-daughter", query: "Architects+Daughter" },
  { name: "Spectral", slug: "spectral", query: "Spectral:ital,wght@0,400;1,400" },
  { name: "Shantell Sans", slug: "shantell-sans", query: "Shantell+Sans:wght@400;500;600;700;800" }
];

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([\s\S]*?)\}/g;
const pick = (body, prop) => (body.match(new RegExp(prop + ":\\s*([^;]+);")) || [])[1]?.trim();

const faces = [];
for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`;
  const css = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

  // Collect the latin faces for this family.
  const collected = [];
  let m;
  while ((m = blockRe.exec(css))) {
    const subset = m[1], body = m[2];
    if (subset !== "latin") continue; // ship latin only
    const src = (body.match(/url\(([^)]+)\)/) || [])[1];
    if (!src) continue;
    const buf = Buffer.from(await (await fetch(src, { headers: { "User-Agent": UA } })).arrayBuffer());
    collected.push({
      style: pick(body, "font-style") || "normal",
      weight: pick(body, "font-weight") || "400",
      hash: createHash("md5").update(buf).digest("hex"),
      buf
    });
  }

  // Group by (style, content hash) — a variable font serves one file for many
  // weights, so those collapse into a single face with a weight range.
  const groups = new Map();
  for (const f of collected) {
    const key = `${f.style}:${f.hash}`;
    if (!groups.has(key)) groups.set(key, { style: f.style, buf: f.buf, weights: [] });
    groups.get(key).weights.push(parseInt(f.weight, 10) || 400);
  }

  let n = 0;
  for (const g of groups.values()) {
    const min = Math.min(...g.weights), max = Math.max(...g.weights);
    const variable = min !== max;
    const wLabel = variable ? "variable" : String(min);
    const file = `${fam.slug}-${g.style}-${wLabel}.woff2`;
    writeFileSync(join(FONTS_DIR, file), g.buf);
    faces.push(
      `@font-face {\n  font-family: "${fam.name}";\n  font-style: ${g.style};\n  font-weight: ${variable ? `${min} ${max}` : min};\n  font-display: swap;\n  src: url("../fonts/${file}") format("woff2");\n}`
    );
    n++;
    console.log(`  ${file}  (${(g.buf.length / 1024).toFixed(0)} KB${variable ? `, weights ${min}–${max}` : ""})`);
  }
  console.log(`${fam.name}: ${n} face(s)`);
}

const banner = "/* GENERATED by fetch-fonts.mjs — self-hosted OFL fonts (latin subset). */\n\n";
writeFileSync(OUT_CSS, banner + faces.join("\n\n") + "\n");
console.log(`\nWrote ${OUT_CSS} (${faces.length} @font-face rules).`);
